### ISSUE TITLE
Use this as an overlay plugin for R-Studio

### ISSUE THREAD

**Issue by dumblob** [klmr/minimappr#1]
I wonder if you plan to make this into an interactive overlay plugin for R-Studio which lacks this great functionality.

Any hints?

**Comment by klmr** [comment]
Sounds like a great idea but since I don’t use RStudio myself, and don’t know its plugin architecture, I have no such plans.

It might also be difficult to adapt this code for live updating code. Normally, IDEs use fundamentally differently structured parsers to perform incremental parsing when code is updated, since re-parsing the entire code is too slow, and will fail on incomplete code.

To illustrate, consider the case where the user is entering a new line of code and has so far written `y <- x +‸` (where `‸` indicates the cursor position). The R function `parse` (which is used here) does not support this. I’m sure that RStudio employs some internal incremental parser (potentially via the ‘[languageserver](https://cran.r-project.org/package=languageserver)’ package) to handle this instead but I don’t know its API.

Furthermore, this project uses ‘ggplot2’ to create the graphical output since this turned out to be easiest, but ‘ggplot2’ is too slow for real-time graphics.

In sum, a reasonable implementation of an RStudio overlay code minimap plugin would probably end up reusing virtually none of the code from this project.

**Comment by dumblob** [comment]
I see. Anyway, thanks for writing this code as demonstration!

(I myself do not use R nor R-Studio - my colleagues do though and they wanted to navigate better so I set out on search for prior art :wink:)
